sudo: false
git:
  depth: 150
branches:
  only:
  - beta
language:
- android
- python
jdk:
- oraclejdk8
python: '3.6'
android:
  components:
  - platform-tools
  - tools
  - extra-android-m2repository
  - build-tools-30.0.0
  - android-30
before_install:
- openssl aes-256-cbc -K $encrypted_c25dbb0d4a25_key -iv $encrypted_c25dbb0d4a25_iv -in Kuroba/app/kuroba_ex.jks.enc -out Kuroba/app/kuroba_ex.jks -d
- yes | sdkmanager "platforms;android-30"
install:
- sudo apt-get update
- sudo apt-get install python3
- sudo apt-get -y install python3-pip
- pip3 install requests
script:
- cd Kuroba || travis_terminate 1;
- chmod +x gradlew || travis_terminate 2;
- ./gradlew assembleBetaRelease --console plain -x lint || travis_terminate 3;
- python3 upload_apk.py https://kuroba.io:8443 beta || travis_terminate 5;
notifications:
  email: false
